// [
//     {
//         "firstName":"Moshe",
//         "lastName":"Levi",
//         "email":"moshelev@hotmail.com",
//         "nickName":"mosheOfficial",
//     },
//     {
//         "firstName":"Ron",
//         "lastName":"Cohen",
//         "email":"ronCohen@hotmail.com",
//         "nickName":"ronco",
//     },
//     {
//         "firstName":"Shay",
//         "lastName":"Ziv",
//         "email":"Shaz1909@hotmail.com",
//         "nickName":"shazy",
//     }
// ]